title: Elder Marketings

source: site

plugins:
  - jekyll-bookshop
  - jekyll-paginate
  - jekyll-archives
  - jekyll-responsive-image
  - jekyll-webp

jekyll-archives:
  enabled:
    - tags
  layout: taxonomy
  permalinks:
    tag: "/tags/:name/"

paginate: 9
paginate_path: "/blogs/page:num/"
# Multiple bookshops can be used on one website,
# or different production / staging locations.
bookshop_locations:
  - ../component-library

exclude:
  - node_modules

include:
  - _cloudcannon # This exposes the live editing data to CloudCannon

# The rest of this array structure will be
# populated by the bookshop-array-structures plugin.
_array_structures:
  content_blocks:
    style: modal

defaults:
  - scope:
      path: ""
    values:
      layout: base

# Image optimization configuration
webp:
  enabled: true
  quality: 75
  img_dir: ["/images"]
  formats: [".jpg", ".jpeg", ".png", ".webp"]
  regenerate: true

# Responsive image sizes
responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 480  # mobile
    - width: 800  # tablet
    - width: 1400 # desktop
  strip: true
  save_to_source: false
  cache: false
