BaseURL: "https://elderpharma.com"
site_title: "Elder Pharmaceuticals"
favicon_icon: "https://elderpharma.com/images/favicon.ico"
favicon_image: "https://elderpharma.com/images/favicon.png"
description: "Elder Pharmaceuticals - A global leader in manufacturing high-quality drug formulations across diverse therapeutic segments. Our innovative products combine effectiveness, affordability, and safety to deliver superior healthcare solutions for patients worldwide."
twitter_image: "/images/feature/feature-hero-two.png"
twitter_site: "@elderpharma"
image: /images/feature/feature-hero.png

_inputs:
  twitter_site:
    type: twitter
    
theme: 
  primary_color: "#002169"
  secondary_color: "#ffffff"
  anchor_color: "#E91B0C"
  background_effects_color: "#d1d9e6"

_inputs:
  twitter_site: 
    type: "twitter"